# Go dependencies
#
# Fetches all required Go dependencies. All Linkerd sources are omitted from the
# resulting image so that artifacts may be built from source over this image.
#
# When this file is changed, run `bin/update-go-deps-shas`.

FROM golang:1.11.5

WORKDIR /linkerd-build

COPY go.mod go.sum ./

# Precompile key slow-to-build dependencies. This list doesn't need to be
# complete for the build to work correctly; the completeness of this list
# only affects the speed of incremental rebuilds of Dependent Dockerfiles.
#
# This list was derived from the output of `find /go/pkg -type f`
# after building the controller.
RUN CGO_ENABLED=0 GOOS=linux go install -mod=readonly \
    github.com/aokoli/goutils \
    github.com/briandowns/spinner \
    github.com/BurntSushi/toml \
    github.com/containernetworking/cni/pkg/version \
    github.com/containernetworking/cni/pkg/skel \
    github.com/containernetworking/cni/pkg/types \
    github.com/containernetworking/cni/pkg/invoke \
    github.com/cpuguy83/go-md2man \
    github.com/cyphar/filepath-securejoin \
    github.com/docker/spdystream \
    github.com/emicklei/proto \
    github.com/evanphx/json-patch \
    github.com/fatih/color \
    github.com/gobwas/glob \
    github.com/ghodss/yaml \
    github.com/golang/protobuf/jsonpb \
    github.com/google/uuid \
    github.com/gorilla/websocket \
    github.com/go-openapi/spec \
    github.com/go-openapi/jsonreference \
    github.com/go-openapi/swag \
    github.com/go-openapi/jsonpointer \
    github.com/grpc-ecosystem/go-grpc-prometheus \
    github.com/huandu/xstrings \
    github.com/inconshreveable/mousetrap \
    github.com/julienschmidt/httprouter \
    github.com/Masterminds/semver \
    github.com/Masterminds/sprig \
    github.com/mailru/easyjson \
    github.com/mattn/go-colorable \
    github.com/mattn/go-isatty \
    github.com/mattn/go-runewidth \
    github.com/mitchellh/go-homedir \
    github.com/nsf/termbox-go \
    github.com/pkg/browser \
    github.com/pkg/errors \
    github.com/prometheus/client_golang/api \
    github.com/prometheus/client_golang/api/prometheus/v1 \
    github.com/prometheus/client_golang/prometheus \
    github.com/prometheus/client_golang/prometheus/promhttp \
    github.com/prometheus/client_model/go \
    github.com/prometheus/common/expfmt \
    github.com/prometheus/common/model \
    github.com/PuerkitoBio/purell \
    github.com/PuerkitoBio/urlesc \
    github.com/russross/blackfriday \
    github.com/satori/go.uuid \
    github.com/shurcooL/vfsgen \
    github.com/sirupsen/logrus \
    github.com/spf13/cobra \
    github.com/wercker/stern \
    google.golang.org/grpc \
    k8s.io/client-go/discovery \
    k8s.io/client-go/kubernetes \
    k8s.io/client-go/kubernetes/scheme \
    k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1 \
    k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1 \
    k8s.io/client-go/kubernetes/typed/apps/v1 \
    k8s.io/client-go/kubernetes/typed/apps/v1beta1 \
    k8s.io/client-go/kubernetes/typed/apps/v1beta2 \
    k8s.io/client-go/kubernetes/typed/authentication/v1 \
    k8s.io/client-go/kubernetes/typed/authentication/v1beta1 \
    k8s.io/client-go/kubernetes/typed/authorization/v1 \
    k8s.io/client-go/kubernetes/typed/authorization/v1beta1 \
    k8s.io/client-go/kubernetes/typed/autoscaling/v1 \
    k8s.io/client-go/kubernetes/typed/autoscaling/v2beta1 \
    k8s.io/client-go/kubernetes/typed/batch/v1 \
    k8s.io/client-go/kubernetes/typed/batch/v1beta1 \
    k8s.io/client-go/kubernetes/typed/batch/v2alpha1 \
    k8s.io/client-go/kubernetes/typed/certificates/v1beta1 \
    k8s.io/client-go/kubernetes/typed/core/v1 \
    k8s.io/client-go/kubernetes/typed/events/v1beta1 \
    k8s.io/client-go/kubernetes/typed/extensions/v1beta1 \
    k8s.io/client-go/kubernetes/typed/networking/v1 \
    k8s.io/client-go/kubernetes/typed/policy/v1beta1 \
    k8s.io/client-go/kubernetes/typed/rbac/v1 \
    k8s.io/client-go/kubernetes/typed/rbac/v1alpha1 \
    k8s.io/client-go/kubernetes/typed/rbac/v1beta1 \
    k8s.io/client-go/kubernetes/typed/scheduling/v1alpha1 \
    k8s.io/client-go/kubernetes/typed/settings/v1alpha1 \
    k8s.io/client-go/kubernetes/typed/storage/v1 \
    k8s.io/client-go/kubernetes/typed/storage/v1alpha1 \
    k8s.io/client-go/kubernetes/typed/storage/v1beta1 \
    k8s.io/client-go/pkg/version \
    k8s.io/client-go/plugin/pkg/client/auth \
    k8s.io/client-go/plugin/pkg/client/auth/azure \
    k8s.io/client-go/plugin/pkg/client/auth/gcp \
    k8s.io/client-go/plugin/pkg/client/auth/oidc \
    k8s.io/client-go/plugin/pkg/client/auth/openstack \
    k8s.io/client-go/rest \
    k8s.io/client-go/rest/watch \
    k8s.io/client-go/tools/auth \
    k8s.io/client-go/tools/cache \
    k8s.io/client-go/tools/clientcmd \
    k8s.io/client-go/tools/pager \
    k8s.io/client-go/transport \
    k8s.io/client-go/util/buffer \
    k8s.io/client-go/util/cert \
    k8s.io/client-go/util/flowcontrol \
    k8s.io/client-go/util/homedir \
    k8s.io/client-go/util/integer \
    k8s.io/client-go/util/jsonpath
