## compile controller services
FROM gcr.io/linkerd-io/go-deps:eda4c910 as golang
WORKDIR /go/src/github.com/linkerd/linkerd2
ENV CGO_ENABLED=0 GOOS=linux

COPY controller/gen controller/gen
COPY controller/k8s controller/k8s
COPY pkg/admin pkg/admin
COPY pkg/flags pkg/flags
COPY pkg/k8s pkg/k8s
COPY pkg/prometheus pkg/prometheus
COPY pkg/tls pkg/tls
COPY pkg/version pkg/version
RUN go build ./pkg/... ./controller/...

COPY identity identity
RUN go install ./identity/cmd/svc

## package runtime
FROM scratch
COPY LICENSE /linkerd/LICENSE
COPY --from=golang /go/bin/svc /bin/identity-svc
ARG LINKERD_VERSION
ENV LINKERD_CONTAINER_VERSION_OVERRIDE=${LINKERD_VERSION}
ENTRYPOINT ["/bin/identity-svc"]
