## compile controller services
FROM gcr.io/linkerd-io/go-deps:b9049684 as golang
WORKDIR /go/src/github.com/linkerd/linkerd2
ENV CGO_ENABLED=0 GOOD=linux

COPY pkg pkg
RUN go build ./pkg/...

COPY identity identity
RUN go install ./identity/cmd/init

## package runtime
FROM scratch
COPY LICENSE /linkerd/LICENSE
COPY --from=golang /go/bin/init /bin/identity-init
ARG LINKERD_VERSION
ENV LINKERD_CONTAINER_VERSION_OVERRIDE=${LINKERD_VERSION}
ENTRYPOINT ["/bin/identity-init"]
